server:
  port: 8072
spring:
  application:
    name: gateway
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 #设置Sleuth的抽样收集概率
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: purchase-order
        uri: lb://purchase-order
        predicates:
          - Path=/purchase-order/**
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: bound-points
        uri: lb://bound-points
        predicates:
          - Path=/bound-points/**
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
ackUri: forward:/fallback
#  redis:
#    host: localhost
#    port: 6379
#    lettuce:
#      pool:
#        max-wait: 100000
#        max-idle: 10
#        max-active: 100
#    timeout: 5000

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-request-size: 20MB
      max-file-size: 10MB

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

#修改hystrix熔断策略
hystrix:
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
          semaphore:
            maxConcurrentRequests: 200

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000



