server:
  port: 8081

spring:
  application:
    name: bound-points-service
#  zipkin:
#    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1 #设置Sleuth的抽样收集概率
  cloud:
    nacos:
      discovery:
#        server-addr: ${NACOS_HOSTNAME}:${NACOS_PORT}
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bound_points?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 20
      # 连接池最小连接数
      min-idle: 20
      # 连接池最大连接数
      max-active: 40
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-connect-error-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 30000
      # 用来检测连接是否有效的sql 必须是一个查询语句
      validation-query: select 'x'
      web-stat-filter:
        enabled: true
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow:
      filter:
        config:
          enabled: true
      #connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALCKPVgxKFibaKZV8lQrgDUqE+suYtySPZ3LPDDZogYb2h9v45NDli0tx894C5mcrcnHbEL6BNEdFb/ufGbUkV0CAwEAAQ==


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#开启feign的熔断机制
feign:
  hystrix:
    enabled: true

#修改hystrix熔断策略
hystrix:
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
          semaphore:
            maxConcurrentRequests: 200
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  level:
    com.xinlus.feign.SmsFeign: debug
swagger:
  enable: true